name: "PR-Voyager"
description: "Publish npm packages for each Pull Request"
author: "kotarella1110"
inputs:
  publish:
    description: "The command to use to build and publish packages"
    required: true
  cwd:
    description: Sets the cwd for the node process. Default to `process.cwd()`
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "package"
  color: "gray-dark"
